<?php

return [
    'cities' => [
        'Jakarta',
        'Surabaya',
        'Bandung',
        'Medan',
        'Semarang',
        'Makassar',
        'Palembang',
        'Tangerang',
        'Depok',
        'Bekasi',
        'Yogyakarta',
        'Malang',
        'Solo',
        'Denpasar',
        'Bogor',
        'Batam',
        'Pekanbaru',
        'Bandar Lampung',
        'Padang',
        'Pontianak',
        'Banjarmasin',
        'Samarinda',
        'Balikpapan',
        'Manado',
        'Cirebon',
        'Serang',
        'Tasikmalaya',
        'Sukabumi',
        'Cilegon',
        'Jambi',
        'Mataram',
        'Kupang',
        'Ambon',
        'Jayapura',
        'Sorong',
        'Ternate',
        'Kendari',
        'Palu',
        'Gorontalo',
        'Bengkulu',
        'Pangkal Pinang',
        'Tanjung Pinang',
    ],
];